### PR TITLE
Remove wiki information from the map check for PoE2

### LINKED ISSUE #243: PoE2 - Remove wiki information from the map check

### PR DESCRIPTION
**Pull request by Trifall**
image

### CODE REVIEW

**Comment by leMicin** [comment]
This tool is used for both PoE1 and PoE2. We want to remove the wiki only when GameType == GameType.PathOfExile2. The game can be determined from the item at Item.Metadata.Game (I think)

**Comment by domialex** [comment]
I don't think map information from poe2wiki has anything interesting to add compared to poe1 maps. Maybe the tileset? Anyways for now it's fine to conditionally hide the wiki for poe2.

**Comment by Trifall** [comment]
image

I reverted it so it should only render when the item is from PoE2, but the styling is a little scuffed because of the two column layout. I was considering rewriting it so that it conditionally chooses between LayoutTwoColumn and LayoutSimple, but I am not sure how to extract the content inside of LeftContent so that it can be rewritten much more concisely instead of copying that block into both branches of the if statement. Either that or somehow passing a class into the LeftContent itself.

**Comment by leMicin** [comment]
I have an idea, but will get to it after I wake up. Thanks for the contribution :)

**Comment by leMicin** [comment]
I have made changes to the TwoLayoutColumn to support this use case.

image

**Comment by leMicin** [comment]
Fixes #243

**Pull request merged**
